apiVersion: apps/v1
kind: Deployment
metadata:
  name: tale-tinkerer-deployment
  labels:
    app: tale-tinkerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tale-tinkerer
  template:
    metadata:
      labels:
        app: tale-tinkerer
    spec:
      containers:
      - name: tale-tinkerer
        image: python:3.9.13
        workingDir: /usr/src/app
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: tale-tinkerer-service
spec:
  selector:
    app: tale-tinkerer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
